# Generated by Django 3.1.2 on 2024-11-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241104_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
    ]
